### PR TITLE
WIP cube tunnel color tweaks and timing fixes

### PR DESCRIPTION
**Pull request by iver56**
This probably needs more tweaking later

### CODE REVIEW

**Comment by cristeahub** [comment]
@sigvef has some changes in this area too, maybe you should do the review, sigve?

**Comment by sigvef** [comment]
Nope, no changes apart from what is in this pull request already. I say we should just merge and iterate for speed!

**Comment by cristeahub** [comment]
⚡️

**Comment by sigvef** [comment]
rune is going to branch out from this branch, slap some fixes on top and then get it into master -o&

**Comment by sigvef** [comment]
\o/, I mean

**Pull request merged**
