### PR TITLE
Update music

### PR DESCRIPTION
**Pull request by sigvef**

### CODE REVIEW

**Comment by stianjensen** [comment]
oooh, what's new 🎉

**Comment by stianjensen** [comment]
Hmm, what happened here actually? Did you delayed the song by a bar somewhere but not update the mp3?

**Comment by stianjensen** [comment]
screen shot 2017-04-04 at 11 00 48

Third edit: apparently I'm blind to this.

**Comment by sigvef** [comment]
There's a new break, a tweak to a different break and I upped the loundness with some crude mastering.

**Pull request merged**
