### PR TITLE
Tweak cube colors and timings

### PR DESCRIPTION
**Pull request by sigvef**
@Raane what do you think?

### CODE REVIEW

**Comment by stianjensen** [comment]
I really like the new timing and rotating animation. I do miss some more colors, though.

**Comment by sigvef** [comment]
What if we add blinky stuff?

**Comment by stianjensen** [comment]
Mayhaps!

**Comment by iver56** [comment]
I like the rotation! We could totally add some blinky color stuff. How about having a texture on the cube walls? Maybe in the same spirit as this: https://www.dwitter.net/d/300 (does not need to be animated though)

**Pull request merged**
